#!/bin/bash

# set the number of nodes
#SBATCH --nodes=1

#SBATCH --cpus-per-task=20

#SBATCH --partition=small

# set max wallclock time
#SBATCH --time=120:00:00

# set name of job
#SBATCH --job-name=tf_bs512ds5z10t6nH12Hd64b1e2

# set number of GPUs
#SBATCH --gres=gpu:1

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=kevin@kdoran.com

# run the application
echo $(pwd)
python ./retinapy_sync/retinapy/src/retinapy/spikeprediction.py \
	--stimulus-pattern ./retinapy_sync/data/ff_noise.h5 \
	--stimulus ./retinapy_sync/data/ff_recorded_noise.pickle \
	--response ./retinapy_sync/data/ff_spike_response.pickle \
	-k Transformer-18ds_992in \
	--lr 5e-4 \
	--epochs 50 \
	--batch-size 512 \
	--steps-til-eval 5000 \
	--zdim 10 \
	--num-tlayers 6 \
	--num-heads 12 \
	--head-dim 64 \
	--vae-beta 1e-2 \
	--labels exp,1,3,1,tf_bs512ds5z10t6nH12Hd64b1e2


