#!/bin/bash

# set the number of nodes
#SBATCH --nodes=1

#SBATCH --cpus-per-task=25

#SBATCH --partition=small

# set max wallclock time
#SBATCH --time=96:00:00

# set name of job
#SBATCH --job-name=vae_1rec_bs256_l1_100_l2_200_l3_300_exp_2_z10d10o_b1e-3

# set number of GPUs
#SBATCH --gres=gpu:1

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=kevin@kdoran.com

# run the application
echo $(pwd)
python ./retinapy_sync/retinapy/src/retinapy/spikeprediction.py \
	--stimulus-pattern ./retinapy_sync/data/ff_noise.h5 \
	--stimulus ./retinapy_sync/data/ff_recorded_noise.pickle \
	--response ./retinapy_sync/data/ff_spike_response.pickle \
	--recording-names Chicken_17_08_21_Phase_00 \
	--lr 5e-4 \
	--epochs 50 \
	--batch-size 256 \
	--steps-til-eval 10000 \
	-k MultiClusterDistField-18ds_992in_100out \
	--zdim 10 \
	--vae-beta 1e-3 \
	--labels exp,1,2,2,vae_1rec_bs256_l1_100_l2_200_l3_300_exp_2_z10d20o_b1e-3


