#!/bin/bash

# set the number of nodes
#SBATCH --nodes=1

#SBATCH --cpus-per-task=25

#SBATCH --partition=small

# set max wallclock time
#SBATCH --time=120:00:00

# set name of job
#SBATCH --job-name=vae_9ds_swide

# set number of GPUs
#SBATCH --gres=gpu:1

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=kevin@kdoran.com

# run the application
echo $(pwd)
python ./retinapy_sync/retinapy/src/retinapy/spikeprediction.py \
	--stimulus-pattern ./retinapy_sync/data/ff_noise.h5 \
	--stimulus ./retinapy_sync/data/ff_recorded_noise.pickle \
	--response ./retinapy_sync/data/ff_spike_response.pickle \
	--lr 5e-4 \
	--epochs 50 \
	--batch-size 64 \
	--steps-til-eval 10000 \
	-k MultiClusterDistField-18ds_992in_100out \
	--zdim=20 \
	--labels exp,1,2,2,vae_wide_18ds_z20d


