#!/bin/bash

# set the number of nodes
#SBATCH --nodes=1

#SBATCH --cpus-per-task=25

#SBATCH --partition=small

# set max wallclock time
#SBATCH --time=96:00:00

# set name of job
#SBATCH --job-name=kd1

# set number of GPUs
#SBATCH --gres=gpu:1

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=kevin@kdoran.com

# run the application
echo $(pwd)
python ./retinapy/src/retinapy/spikeprediction.py \
	--stimulus-pattern ./data/ff_noise.h5 \
	--stimulus ./data/ff_recorded_noise.pickle \
	--response ./data/ff_spike_response.pickle \
	--lr 5e-4 \
	--epochs 20 \
	--batch-size 256 \
	--steps-til-eval 5000 \
	-k MultiClusterDistField-9ds_3174in_198out \
	--labels exp,1,2,1,all_recs_vae_hpc


